name: Haiku Commit Art Generator
on:
  pull_request
  
jobs: 
 generate_haiku_art:
    runs-on: ubuntu-latest
    permissions:
        contents: write 
        pull-requests: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate haiku art
        uses: henriettelienrebnor/Fagdag@main
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          PR_NUMBER: ${{ github.event.number }}